### ISSUE TITLE
능력 적용 중 오류

### ISSUE THREAD

**Issue by abcd0912** [noonmaru/heroes#127]
능력 빌드 이후 서버 구동중 다음 메세지가 뜨며 적용되지 않습니다.  해결법 아시는분 계신가요?

[18:13:27 WARN]: java.lang.IllegalStateException: Not found ability made.by.parksigong.time
[18:13:27 WARN]:        at com.github.noonmaru.psychics.PsychicManager.loadPsychics$psychics_common(PsychicManager.kt:224)
[18:13:27 WARN]:        at com.github.noonmaru.psychics.plugin.PsychicPlugin.loadModules(PsychicPlugin.kt:72)
[18:13:27 WARN]:        at com.github.noonmaru.psychics.plugin.PsychicPlugin.onEnable(PsychicPlugin.kt:52)
[18:13:27 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[18:13:27 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[18:13:27 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[18:13:27 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:501)
[18:13:27 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:415)
[18:13:27 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468)
[18:13:27 WARN]:        at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:237)
[18:13:27 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939)
[18:13:27 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[18:13:27 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by paring-chan** [comment]
능력 프로젝트 폴더에 gradle.properties를 만들고 group을 추가해주시면 (아마도 될거에요) 아니면 src/main/resources/ability.yml에 가서 main 부분을 바꿔주시면 될거에요.
