### ISSUE TITLE
해결 가능한 문제 입니까?  java.lang.NoSuchMethodError: 'org.bukkit.Server$Spigot org.bukkit.Bukkit.spigot()'

### ISSUE THREAD

**Issue by muqhc** [noonmaru/heroes#128]
그나저나 여기에 물어봐도 되는건지 모르겠네요....
```
[19:46:12] [Server thread/WARN]: java.lang.NoSuchMethodError: 'org.bukkit.Server$Spigot org.bukkit.Bukkit.spigot()'
[19:46:12] [Server thread/WARN]:        at com.github.noonmaru.psychics.PsychicConcept.initialize$psychics_common(PsychicConcept.kt:109)
[19:46:12] [Server thread/WARN]:        at com.github.noonmaru.psychics.PsychicManager.loadPsychics$psychics_common(PsychicManager.kt:207)
[19:46:12] [Server thread/WARN]:        at com.github.noonmaru.psychics.plugin.PsychicPlugin.loadModules(PsychicPlugin.kt:72)
[19:46:12] [Server thread/WARN]:        at com.github.noonmaru.psychics.plugin.PsychicPlugin.onEnable(PsychicPlugin.kt:52)
[19:46:12] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[19:46:12] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:343)
[19:46:12] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479)
[19:46:12] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:480)
[19:46:12] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:406)
[19:46:12] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:426)
[19:46:12] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:203)
[19:46:12] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:786)
[19:46:12] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:155)
[19:46:12] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:832)
```
플러그인 활성화중 일어난 문제입니다.

해결할 방법이 있을까요?

**Comment by muqhc** [comment]
이런.......................... 죄송합니다...............
CraftBukkit을 사용한 문제였네요
