### ISSUE TITLE
능력 로더오류?

### ISSUE THREAD

**Issue by sharkzhs83** [noonmaru/heroes#131]
서버에 능력을 만들고 적용시켰는데 이런 오류가 뜹니다

[19:52:07 WARN]: java.lang.ClassNotFoundException: com.github.noonmaru.psychic.ability.sample.Sample
[19:52:07 WARN]:        at com.github.noonmaru.psychics.loader.AbilityLoader.findClass$psychics_common(AbilityLoader.kt:77)
[19:52:07 WARN]:        at com.github.noonmaru.psychics.loader.AbilityClassLoader.findClass(AbilityClassLoader.kt:38)
[19:52:07 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
[19:52:07 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[19:52:07 WARN]:        at java.lang.Class.forName0(Native Method)
[19:52:07 WARN]:        at java.lang.Class.forName(Class.java:348)
[19:52:07 WARN]:        at com.github.noonmaru.psychics.loader.AbilityLoader.load$psychics_common(AbilityLoader.kt:41)
[19:52:07 WARN]:        at com.github.noonmaru.psychics.PsychicManager.loadAbilities$psychics_common(PsychicManager.kt:140)
[19:52:07 WARN]:        at com.github.noonmaru.psychics.plugin.PsychicPlugin.loadModules(PsychicPlugin.kt:71)
[19:52:07 WARN]:        at com.github.noonmaru.psychics.plugin.PsychicPlugin.onEnable(PsychicPlugin.kt:52)
[19:52:07 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[19:52:07 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[19:52:07 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[19:52:07 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501)
[19:52:07 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415)
[19:52:07 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:464)
[19:52:07 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239)
[19:52:07 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:935)
[19:52:07 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173)
[19:52:07 WARN]:        at java.lang.Thread.run(Thread.java:748)
[19:52:07 WARN]: [Psychics] Failed to load Ability sharkzhs.fireball.jar

왜 이런 거죠?

**Comment by sharkzhs83** [comment]
Gradle 빌드를 각각 해봤는데 sample에도 오류가 뜨네요.
![image](https://user-images.githubusercontent.com/88832594/129446681-8b07d8b8-4713-44ff-81b8-94aaeb7b9dae.png)
