### ISSUE TITLE
eval 오류 ?!?

### ISSUE THREAD

**Issue by muqhc** [noonmaru/heroes#132]
어떻게 해결할 수 있나요?
```
[20:35:30 WARN]: java.lang.IllegalArgumentException: Failed to render template token ${common.cooldown-ticks * 0.05}
[20:35:30 WARN]:        at com.github.noonmaru.psychics.tap.template.TemplateSupportKt.renderTemplates(TemplateSupport.kt:77)
[20:35:30 WARN]:        at com.github.noonmaru.psychics.tap.template.TemplateSupportKt.renderTemplatesAll(TemplateSupport.kt:31)
[20:35:30 WARN]:        at com.github.noonmaru.psychics.AbilityConcept.initialize$psychics_common(AbilityConcept.kt:196)
[20:35:30 WARN]:        at com.github.noonmaru.psychics.PsychicManager.loadPsychics$psychics_common(PsychicManager.kt:229)
[20:35:30 WARN]:        at com.github.noonmaru.psychics.PsychicManager.reload$psychics_common(PsychicManager.kt:62)
[20:35:30 WARN]:        at com.github.noonmaru.psychics.plugin.PsychicPlugin.reloadPsychics(PsychicPlugin.kt:114)
[20:35:30 WARN]:        at com.github.noonmaru.psychics.command.CommandPsychic$register$1$6$1.invoke(CommandPsychic.kt:101)
[20:35:30 WARN]:        at com.github.noonmaru.psychics.command.CommandPsychic$register$1$6$1.invoke(CommandPsychic.kt:41)
[20:35:30 WARN]:        at com.github.noonmaru.psychics.kommand.KommandDispatcher.dispatch$kommand(KommandDispatcher.kt:110)
[20:35:30 WARN]:        at com.github.noonmaru.psychics.kommand.KommandAdapter.onCommand(KommandDispatcher.kt:250)
[20:35:30 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[20:35:30 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[20:35:30 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:807)
[20:35:30 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:769)
[20:35:30 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:411)
[20:35:30 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:378)
[20:35:30 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1204)
[20:35:30 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:992)
[20:35:30 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173)
[20:35:30 WARN]:        at java.base/java.lang.Thread.run(Thread.java:832)
[20:35:30 WARN]: Caused by: java.lang.IllegalArgumentException: Failed to evaluate 20 * 0.05
[20:35:30 WARN]:        at com.github.noonmaru.psychics.tap.template.Template$Expression.renderValue(TemplateSupport.kt:174)
[20:35:30 WARN]:        at com.github.noonmaru.psychics.tap.template.TemplateSupportKt.renderTemplates(TemplateSupport.kt:71)
[20:35:30 WARN]:        ... 19 more
```
해결 못 하는 문제 같으면 그것 또한 말씀 해주시면 감사하겠습니다.

**Comment by muqhc** [comment]
해결 못 하는 것 같으면 그것 또한 얘기 해주세요.

**Comment by muqhc** [comment]
잉.... 그냥 eval 안 쓰고 해볼게요
