### ISSUE TITLE
능력로드버그

### ISSUE THREAD

**Issue by xoghksdl** [noonmaru/heroes#133]
[11:25:44] [Server thread/WARN]: java.lang.NoSuchMethodError: 'org.bukkit.configuration.file.YamlConfiguration org.bukkit.Server$Spigot.getSpigotConfig()'
[11:25:44] [Server thread/WARN]:        at com.github.noonmaru.psychics.PsychicConcept.initialize$psychics_common(PsychicConcept.kt:109)
[11:25:44] [Server thread/WARN]:        at com.github.noonmaru.psychics.PsychicManager.loadPsychics$psychics_common(PsychicManager.kt:207)
[11:25:44] [Server thread/WARN]:        at com.github.noonmaru.psychics.plugin.PsychicPlugin.loadModules(PsychicPlugin.kt:72)
[11:25:44] [Server thread/WARN]:        at com.github.noonmaru.psychics.plugin.PsychicPlugin.onEnable(PsychicPlugin.kt:52)
[11:25:44] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[11:25:44] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
[11:25:44] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[11:25:44] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:494)
[11:25:44] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:408)
[11:25:44] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:435)
[11:25:44] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:218)
[11:25:44] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:808)
[11:25:44] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164)
[11:25:44] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:829)
[11:25:44] [Server thread/WARN]: [Psychics] Failed to load Psychic sample.yml

뭐가 잘못된걸까요? ㅠㅠ psychics 파일에 yml 파일넣고 능력도 abilities파일에 넣었는데 로드가 안돼네요 ㅠㅠ

**Comment by paring-chan** [comment]
https://github.com/monun/psychics 여기로 가시는걸 추천드립니다 여기로 레포 옮긴거같아요
