### ISSUE TITLE
능력적용하려는데

### ISSUE THREAD

**Issue by cookin12** [noonmaru/heroes#137]
[12:15:26 INFO]: MlnedApple issued server command: /psychics attach 닉네임 fly
[12:17:03 INFO]: MlnedApple issued server command: /psy info
[12:17:03 WARN]: java.lang.NoClassDefFoundError: com/github/monun/invfx/InvFX
[12:17:03 WARN]:        at Psychics_3.jar//com.github.monun.psychics.invfx.InvPsychic.create(InvPsychic.kt:20)
[12:17:03 WARN]:        at Psychics_3.jar//com.github.monun.psychics.command.CommandPsychic.info(CommandPsychic.kt:109)
[12:17:03 WARN]:        at Psychics_3.jar//com.github.monun.psychics.command.CommandPsychic.access$info(CommandPsychic.kt:41)
[12:17:03 WARN]:        at Psychics_3.jar//com.github.monun.psychics.command.CommandPsychic$register$1$4$3.invoke(CommandPsychic.kt:85)
[12:17:03 WARN]:        at Psychics_3.jar//com.github.monun.psychics.command.CommandPsychic$register$1$4$3.invoke(CommandPsychic.kt:41)
[12:17:03 WARN]:        at Psychics_3.jar//com.github.monun.psychics.kommand.KommandDispatcher.dispatch$kommand(KommandDispatcher.kt:110)
[12:17:03 WARN]:        at Psychics_3.jar//com.github.monun.psychics.kommand.KommandAdapter.onCommand(KommandDispatcher.kt:250)
[12:17:03 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[12:17:03 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[12:17:03 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:838)
[12:17:03 WARN]:        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2257)
[12:17:03 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2068)
[12:17:03 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2049)
[12:17:03 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[12:17:03 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[12:17:03 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[12:17:03 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[12:17:03 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[12:17:03 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[12:17:03 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1418)
[12:17:03 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192)
[12:17:03 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[12:17:03 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1396)
[12:17:03 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1389)
[12:17:03 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[12:17:03 WARN]:        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1367)
[12:17:03 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1278)
[12:17:03 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[12:17:03 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
라고 뜨면서 안되요

**Comment by HotoRas** [comment]
서버의 `Minecraft 버전`, `구동기(Paper 지원 여부 필수)`, `적용되어 있는 플러그인의 목록`을 알려주실 수 있나요?
