### ISSUE TITLE
Paper 서버 plugin load 관련 문제

### ISSUE THREAD

**Issue by josef-gangl** [noonmaru/heroes#138]
[21:32:44 ERROR]: Could not load 'plugins\Psychics.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.16
        at org.bukkit.craftbukkit.v1_13_R2.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:226) ~[patched_1.13.2.jar:git-Paper-657]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:130) ~[patched_1.13.2.jar:git-Paper-657]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:334) ~[patched_1.13.2.jar:git-Paper-657]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:255) ~[patched_1.13.2.jar:git-Paper-657]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:331) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:235) ~[patched_1.13.2.jar:git-Paper-657]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787) ~[patched_1.13.2.jar:git-Paper-657]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_361]
Wiki대로 Paper 서버 plugins 폴더에 의존성 플러그인과 Psychics 최신 버전을 넣었습니다.
이 문제의 원인이 뭔지 가장 빠른 시일내로 알려주십시요

**Comment by josef-gangl** [comment]
해결됨.
