### ISSUE TITLE
1.16.4 아머스탠드 오류

### ISSUE THREAD

**Issue by ejun21941** [noonmaru/heroes#84]
[15:31:48 WARN]: [Psychics] Task #11 for Psychics v0.9.3 generated an exception
java.lang.NoClassDefFoundError: com/comphenix/protocol/wrappers/Pair
        at com.github.noonmaru.psychics.tap.v1_16_R3.protocol.NMSPacketSupport.entityEquipment(NMSPacketSupport.kt:119) ~[?:?]
        at com.github.noonmaru.psychics.tap.fake.internal.FakeEntityImpl.spawnTo(FakeEntityImpl.kt:418) ~[?:?]
        at com.github.noonmaru.psychics.tap.fake.internal.FakeEntityImpl.computeTracker(FakeEntityImpl.kt:393) ~[?:?]
        at com.github.noonmaru.psychics.tap.fake.internal.FakeEntityImpl.updateTrackers(FakeEntityImpl.kt:374) ~[?:?]
        at com.github.noonmaru.psychics.tap.fake.internal.FakeEntityImpl.update$api(FakeEntityImpl.kt:286) ~[?:?]
        at com.github.noonmaru.psychics.tap.fake.internal.FakeEntityServerImpl.updateEntities(FakeEntityServerImpl.kt:123) ~[?:?]
        at com.github.noonmaru.psychics.tap.fake.internal.FakeEntityServerImpl.update(FakeEntityServerImpl.kt:98) ~[?:?]        at com.github.noonmaru.psychics.plugin.SchedulerTask.run(SchedulerTask.kt:36) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-279]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.4.jar:git-Paper-279]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1297) ~[patched_1.16.4.jar:git-Paper-279]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-279]        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.4.jar:git-Paper-279]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1000) ~[patched_1.16.4.jar:git-Paper-279]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-279]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
[15:31:48 WARN]: [Psychics] Task #11 for Psychics v0.9.3 generated an exception
java.lang.NoClassDefFoundError: com/comphenix/protocol/wrappers/Pair
        at com.github.noonmaru.psychics.tap.v1_16_R3.protocol.NMSPacketSupport.entityEquipment(NMSPacketSupport.kt:119) ~[?:?]
        at com.github.noonmaru.psychics.tap.fake.internal.FakeEntityImpl.spawnTo(FakeEntityImpl.kt:418) ~[?:?]
        at com.github.noonmaru.psychics.tap.fake.internal.FakeEntityImpl.computeTracker(FakeEntityImpl.kt:393) ~[?:?]
        at com.github.noonmaru.psychics.tap.fake.internal.FakeEntityImpl.updateTrackers(FakeEntityImpl.kt:374) ~[?:?]
        at com.github.noonmaru.psychics.tap.fake.internal.FakeEntityImpl.update$api(FakeEntityImpl.kt:286) ~[?:?]
        at com.github.noonmaru.psychics.tap.fake.internal.FakeEntityServerImpl.updateEntities(FakeEntityServerImpl.kt:123) ~[?:?]
        at com.github.noonmaru.psychics.tap.fake.internal.FakeEntityServerImpl.update(FakeEntityServerImpl.kt:98) ~[?:?]        at com.github.noonmaru.psychics.plugin.SchedulerTask.run(SchedulerTask.kt:36) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-279]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.4.jar:git-Paper-279]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1297) ~[patched_1.16.4.jar:git-Paper-279]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-279]        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.4.jar:git-Paper-279]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1000) ~[patched_1.16.4.jar:git-Paper-279]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-279]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
[15:31:48 WARN]: [Psychics] Task #11 for Psychics v0.9.3 generated an exception
java.lang.NoClassDefFoundError: com/comphenix/protocol/wrappers/Pair
        at com.github.noonmaru.psychics.tap.v1_16_R3.protocol.NMSPacketSupport.entityEquipment(NMSPacketSupport.kt:119) ~[?:?]
        at com.github.noonmaru.psychics.tap.fake.internal.FakeEntityImpl.spawnTo(FakeEntityImpl.kt:418) ~[?:?]
        at com.github.noonmaru.psychics.tap.fake.internal.FakeEntityImpl.computeTracker(FakeEntityImpl.kt:393) ~[?:?]
        at com.github.noonmaru.psychics.tap.fake.internal.FakeEntityImpl.updateTrackers(FakeEntityImpl.kt:374) ~[?:?]
        at com.github.noonmaru.psychics.tap.fake.internal.FakeEntityImpl.update$api(FakeEntityImpl.kt:286) ~[?:?]
        at com.github.noonmaru.psychics.tap.fake.internal.FakeEntityServerImpl.updateEntities(FakeEntityServerImpl.kt:123) ~[?:?]
        at com.github.noonmaru.psychics.tap.fake.internal.FakeEntityServerImpl.update(FakeEntityServerImpl.kt:98) ~[?:?]        at com.github.noonmaru.psychics.plugin.SchedulerTask.run(SchedulerTask.kt:36) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-279]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.4.jar:git-Paper-279]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1297) ~[patched_1.16.4.jar:git-Paper-279]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-279]        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.4.jar:git-Paper-279]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1000) ~[patched_1.16.4.jar:git-Paper-279]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-279]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
[15:31:48 WARN]: [Psychics] Task #11 for Psychics v0.9.3 generated an exception
java.lang.NoClassDefFoundError: com/comphenix/protocol/wrappers/Pair
        at com.github.noonmaru.psychics.tap.v1_16_R3.protocol.NMSPacketSupport.entityEquipment(NMSPacketSupport.kt:119) ~[?:?]
        at com.github.noonmaru.psychics.tap.fake.internal.FakeEntityImpl.spawnTo(FakeEntityImpl.kt:418) ~[?:?]
        at com.github.noonmaru.psychics.tap.fake.internal.FakeEntityImpl.computeTracker(FakeEntityImpl.kt:393) ~[?:?]
        at com.github.noonmaru.psychics.tap.fake.internal.FakeEntityImpl.updateTrackers(FakeEntityImpl.kt:374) ~[?:?]
        at com.github.noonmaru.psychics.tap.fake.internal.FakeEntityImpl.update$api(FakeEntityImpl.kt:286) ~[?:?]
        at com.github.noonmaru.psychics.tap.fake.internal.FakeEntityServerImpl.updateEntities(FakeEntityServerImpl.kt:123) ~[?:?]
        at com.github.noonmaru.psychics.tap.fake.internal.FakeEntityServerImpl.update(FakeEntityServerImpl.kt:98) ~[?:?]        at com.github.noonmaru.psychics.plugin.SchedulerTask.run(SchedulerTask.kt:36) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-279]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.4.jar:git-Paper-279]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1297) ~[patched_1.16.4.jar:git-Paper-279]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-279]        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.4.jar:git-Paper-279]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1000) ~[patched_1.16.4.jar:git-Paper-279]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-279]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
[15:31:48 WARN]: [Psychics] Task #11 for Psychics v0.9.3 generated an exception
java.lang.NoClassDefFoundError: com/comphenix/protocol/wrappers/Pair
        at com.github.noonmaru.psychics.tap.v1_16_R3.protocol.NMSPacketSupport.entityEquipment(NMSPacketSupport.kt:119) ~[?:?]
        at com.github.noonmaru.psychics.tap.fake.internal.FakeEntityImpl.spawnTo(FakeEntityImpl.kt:418) ~[?:?]
        at com.github.noonmaru.psychics.tap.fake.internal.FakeEntityImpl.computeTracker(FakeEntityImpl.kt:393) ~[?:?]
        at com.github.noonmaru.psychics.tap.fake.internal.FakeEntityImpl.updateTrackers(FakeEntityImpl.kt:374) ~[?:?]
        at com.github.noonmaru.psychics.tap.fake.internal.FakeEntityImpl.update$api(FakeEntityImpl.kt:286) ~[?:?]
        at com.github.noonmaru.psychics.tap.fake.internal.FakeEntityServerImpl.updateEntities(FakeEntityServerImpl.kt:123) ~[?:?]
        at com.github.noonmaru.psychics.tap.fake.internal.FakeEntityServerImpl.update(FakeEntityServerImpl.kt:98) ~[?:?]        at com.github.noonmaru.psychics.plugin.SchedulerTask.run(SchedulerTask.kt:36) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-279]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.4.jar:git-Paper-279]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1297) ~[patched_1.16.4.jar:git-Paper-279]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-279]        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.4.jar:git-Paper-279]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1000) ~[patched_1.16.4.jar:git-Paper-279]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-279]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
부메랑 아이템인 금괴를 우클릭 하면 나가는소리도 나고 엔티티도 데미지를 받는데 이런 오류가 콘솔창에 뜨며 아머스탠드가 안보입니다 (양털들)

**Comment by ejun21941** [comment]
@noonmaru

**Comment by noonmaru** [comment]
최신버전의 ProtocolLib이 필요합니다.

내장되어있는 docker-compose.yml을 이용한 도커 환경을 구성해보세요.

자동으로 플러그인을 다운받습니다
