### ISSUE TITLE
psychics paper 서버 적용 오류

### ISSUE THREAD

**Issue by 2006Ted** [noonmaru/heroes#91]
java.lang.IllegalArgumentException: Failed to render template token ${magic-archer.arrow-delay-ticks / 20.0}
[16:45:34 WARN]:        at com.github.noonmaru.psychics.tap.template.TemplateSupportKt.renderTemplates(TemplateSupport.kt:77)
[16:45:34 WARN]:        at com.github.noonmaru.psychics.tap.template.TemplateSupportKt.renderTemplatesAll(TemplateSupport.kt:31)
[16:45:34 WARN]:        at com.github.noonmaru.psychics.AbilityConcept.initialize$psychics_common(AbilityConcept.kt:196)
[16:45:34 WARN]:        at com.github.noonmaru.psychics.PsychicManager.loadPsychics$psychics_common(PsychicManager.kt:229)
[16:45:34 WARN]:        at com.github.noonmaru.psychics.plugin.PsychicPlugin.loadModules(PsychicPlugin.kt:72)
[16:45:34 WARN]:        at com.github.noonmaru.psychics.plugin.PsychicPlugin.onEnable(PsychicPlugin.kt:52)
[16:45:34 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[16:45:34 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[16:45:34 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[16:45:34 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501)
[16:45:34 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415)
[16:45:34 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:469)
[16:45:34 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239)
[16:45:34 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:936)
[16:45:34 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178)
[16:45:34 WARN]:        at java.base/java.lang.Thread.run(Thread.java:832)
[16:45:34 WARN]: Caused by: java.lang.IllegalArgumentException: Failed to evaluate 8 / 20.0
[16:45:34 WARN]:        at com.github.noonmaru.psychics.tap.template.Template$Expression.renderValue(TemplateSupport.kt:174)
[16:45:34 WARN]:        at com.github.noonmaru.psychics.tap.template.TemplateSupportKt.renderTemplates(TemplateSupport.kt:71)
[16:45:34 WARN]:        ... 15 more
[16:45:34 WARN]: [Psychics] Failed to load Psychic sample.yml

이렇게 되는데 어떻게 해야 하나요

**Comment by ghost** [comment]
#66

**Comment by ghost** [comment]
JRE혹은 JDK를 8이나 11로 설정하시고 올바르게 의존성을 넣은 뒤 서버를 돌려보세요.

해걸되셨다면 이슈 닫아주세요.
